gg.setRanges(gg.REGION_C_ALLOC)
gg.processResume()
gg.searchNumber('"67109377"', gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1)
revert = gg.getResults(100000, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll('"700381"', gg.TYPE_DWORD)

gg.clearResults()
gg.processResume()
gg.searchNumber('"135682"', gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1)
revert = gg.getResults(100000, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll('"700381"', gg.TYPE_DWORD)

gg.clearResults()
gg.processResume()
gg.searchNumber('"131331"', gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1)
revert = gg.getResults(100000, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll('"700381"', gg.TYPE_DWORD)

gg.clearResults()
gg.processResume()
gg.searchNumber('"134659"', gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1)
revert = gg.getResults(100000, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll('"700381"', gg.TYPE_DWORD)

gg.clearResults()
gg.processResume()
gg.searchNumber('"131586"', gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1)
revert = gg.getResults(100000, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll('"700381"', gg.TYPE_DWORD)

gg.clearResults()
gg.processResume()
gg.searchNumber('"131842"', gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1)
revert = gg.getResults(100000, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll('"700381"', gg.TYPE_DWORD)

gg.clearResults()
gg.searchNumber('"132098"', gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1)
revert = gg.getResults(100000, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll('"700381"', gg.TYPE_DWORD)

gg.clearResults()
gg.searchNumber('"133634"', gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1)
revert = gg.getResults(100000, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll('"700381"', gg.TYPE_DWORD)

gg.clearResults()
gg.searchNumber('"134402"', gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1)
revert = gg.getResults(100000, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll('"700381"', gg.TYPE_DWORD)

gg.clearResults()
gg.searchNumber('"131330"', gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1)
revert = gg.getResults(100000, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll('"700381"', gg.TYPE_DWORD)

gg.clearResults()
gg.processResume()
gg.searchNumber('"12547"', gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1)
revert = gg.getResults(100000, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll('"700381"', gg.TYPE_DWORD)

gg.clearResults()
gg.toast("Antiban Activated")